networks:
    turla_network:
        external: true

services:
    turla_backoffice:
        container_name: turla_backoffice
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5225:80"
        networks:
            - turla_network
